export const ADD_USER = "ADD_USER"
export const PATIENT_DATA = "PATIENT_DATA"
export const PATIENT_ALL_DATA = "PATIENT_ALL_DATA"
export const INSURANCE_DATA = "INSURANCE_DATA" 
export const CHART_NOTES_DATA = "CHART_NOTES_DATA" 
export const CHART_NOTES = "CHART_NOTES" 
export const FACILITY_CLAIM = "FACILITY_CLAIM" 
export const RENDERING_DATA = "RENDERING_DATA" 
export const REFERRING_DATA = "REFERRING_DATA" 
export const CHART_NOTES_CLAIM = "CHART_NOTES_CLAIM" 
 
export const EDIT_SETTING_ID = "EDIT_SETTING_ID"
export const SHOW_SETTING_ID = "SHOW_SETTING_ID"

export const EDIT_CPT_ID = "EDIT_CPT_ID"
export const SHOW_CPT_ID = "SHOW_CPT_ID"

export const EDIT_ICD_ID = "EDIT_ICD_ID"
export const SHOW_ICD_ID = "SHOW_ICD_ID"


export const EDIT_FACILITY_ID = "EDIT_FACILITY_ID"
export const SHOW_FACILITY_ID = "SHOW_FACILITY_ID"


export const EDIT_PROVIDER_ID = "EDIT_PROVIDER_ID"
export const SHOW_PROVIDER_ID = "SHOW_PROVIDER_ID"

export const EDIT_TASK_ID = "EDIT_TASK_ID"
export const SHOW_TASK_ID = "SHOW_TASK_ID"

export const SHOW_PATIENT_ID = "SHOW_PATIENT_ID"


export const SHOW_INSURANCE_ID = "SHOW_INSURANCE_ID"
export const EDIT_INSURANCE_ID = "EDIT_INSURANCE_ID"


export const SHOW_BILLING_ID = "SHOW_BILLING_ID"
export const EDIT_BILLING_ID = "EDIT_BILLING_ID"

export const SHOW_ALERT_ID = "SHOW_ALERT_ID"
export const EDIT_ALERT_ID = "EDIT_ALERT_ID"
export const PROVIDER_TYPE = "PROVIDER_TYPE"
// export const PROFILE_ID = "PROFILE_ID"
export const MY_PROFILE_ID = "MY_PROFILE_ID"
export const MY_PROFILE_EDIT_ID = "MY_PROFILE_EDIT_ID"
// export const PROFILE_EDIT_ID = "PROFILE_EDIT_ID"

