import {combineReducers} from 'redux'
import {
  userReducerComp,
  patientReducerComp,
  patientAllReducerComp,
  insuranceReducerComp,
  chartNotesDataReducerComp,
  facilityClaimReducerComp,
  chartNotesClaimReducerComp,
  renderingReducerComp,
  referingReducerComp,
  chartNotesReducerComp,
  settingIdEditReducer,
  settingIdShowReducerComp,
  cptIdEditReducer,
  cptIdShowReducerComp, 
  icdIdEditReducer,
  icdIdShowReducerComp, 
  facilityIdEditReducer,
  facilityIdShowReducerComp,
  providerIdShowReducerComp, 
  providerIdEditReducer,
  patientIdShowReducerComp,
  insuranceIdShowReducerComp,
  insuranceIdEditReducer,
  billingIdShowReducerComp,
  billingIdEditReducer,
  alertIdShowReducerComp,
  alertIdEditReducer,
  taskIdShowReducerComp,
  taskIdEditReducer,
  providerTypeReducer,
  // profileIdReducer,
  myProfileIdReducer,
  // profileeditIdReducer
} from './reducer'
 
const rootRed = combineReducers({
  userReducerComp,
  patientReducerComp,
  patientAllReducerComp,
  insuranceReducerComp,
  chartNotesDataReducerComp,
  facilityClaimReducerComp,
  chartNotesClaimReducerComp,
  renderingReducerComp,
  referingReducerComp,
  chartNotesReducerComp,
  settingIdEditReducer,
  settingIdShowReducerComp,
  cptIdEditReducer,
  cptIdShowReducerComp,
  icdIdEditReducer,
  icdIdShowReducerComp,
  facilityIdEditReducer,
  facilityIdShowReducerComp,
  providerIdShowReducerComp,
  providerIdEditReducer,
  patientIdShowReducerComp,
  insuranceIdShowReducerComp, 
  insuranceIdEditReducer,
  billingIdShowReducerComp,
  billingIdEditReducer,
  alertIdShowReducerComp,
  alertIdEditReducer,
  taskIdShowReducerComp,
  taskIdEditReducer,
  providerTypeReducer,
  // profileIdReducer,
  // profileeditIdReducer,
  myProfileIdReducer,
})

export default rootRed
