const permissions = [
  {
    role: 'farmer',
    permissions: [
      {
        add_users: false,
        view_users: false,
        update_users: false,
        block_users: false,
        delete_users: false,
      },
      {
        add_vendor: false,
        view_vendor: true,
        update_vendor: false,
        delete_vendor: false,
        block_vendor: false,
      },
      {
        add_wholesaler: false,
        view_wholesaler: true,
        update_wholesaler: false,
        delete_wholesaler: false,
        block_wholesaler: false,
      },
      {
        add_farmer: false,
        view_farmer: true,
        update_farmer: false,
        delete_farmer: false,
        block_farmer: false,
      },
      {
        add_machinery: false,
        view_machinery: true,
        update_machinery: false,
        delete_machinery: false,
        block_machinery: false,
      },
      {
        add_seeds: false,
        view_seeds: true,
        update_seeds: false,
        delete_seeds: false,
        block_seeds: false,
      },
      {
        add_raw_material: false,
        view_raw_material: true,
        update_raw_material: false,
        delete_raw_material: false,
        block_raw_material: false,
      },
      {
        add_land_broker: false,
        view_land_broker: true,
        update_land_broker: false,
        delete_land_broker: false,
        block_land_broker: false,
      },
      {
        add_transport: false,
        view_transport: true,
        update_transport: false,
        delete_transport: false,
        block_transport: false,
      },
      {
        add_accounts: false,
        view_accounts: false,
        update_accounts: false,
        delete_accounts: false,
        block_accounts: false,
      },
      {
        agriculture: true,
      },
      {
        logistics: true,
      },
    ],
  },
  {
    role: 'admin',
    permissions: [
      {
        add_users: true,
        view_users: true,
        update_users: true,
        block_users: true,
        delete_users: true,
      },
      {
        add_vendor: true,
        view_vendor: true,
        update_vendor: true,
        delete_vendor: true,
        block_vendor: true,
      },
      {
        add_wholesaler: true,
        view_wholesaler: true,
        update_wholesaler: true,
        delete_wholesaler: true,
        block_wholesaler: true,
      },
      {
        add_farmer: true,
        view_farmer: true,
        update_farmer: true,
        delete_farmer: true,
        block_farmer: true,
      },
      {
        add_machinery: true,
        view_machinery: true,
        update_machinery: true,
        delete_machinery: true,
        block_machinery: true,
      },
      {
        add_seeds: true,
        view_seeds: true,
        update_seeds: true,
        delete_seeds: true,
        block_seeds: true,
      },
      {
        add_raw_material: true,
        view_raw_material: true,
        update_raw_material: true,
        delete_raw_material: true,
        block_raw_material: true,
      },
      {
        add_land_broker: true,
        view_land_broker: true,
        update_land_broker: true,
        delete_land_broker: true,
        block_land_broker: true,
      },
      {
        add_transport: true,
        view_transport: true,
        update_transport: true,
        delete_transport: true,
        block_transport: true,
      },
      {
        add_accounts: true,
        view_accounts: true,
        update_accounts: true,
        delete_accounts: true,
        block_accounts: true,
      },
      {
        agriculture: true,
      },
      {
        logistics: true,
      },
    ],
  },
  {
    role: 'vendor',
    permissions: [
      {
        add_users: false,
        view_users: false,
        update_users: false,
        block_users: false,
        delete_users: false,
      },
      {
        add_vendor: false,
        view_vendor: true,
        update_vendor: false,
        delete_vendor: false,
        block_vendor: false,
      },
      {
        add_wholesaler: false,
        view_wholesaler: true,
        update_wholesaler: false,
        delete_wholesaler: false,
        block_wholesaler: false,
      },
      {
        add_farmer: false,
        view_farmer: true,
        update_farmer: false,
        delete_farmer: false,
        block_farmer: false,
      },
      {
        add_machinery: false,
        view_machinery: false,
        update_machinery: false,
        delete_machinery: false,
        block_machinery: false,
      },
      {
        add_seeds: false,
        view_seeds: false,
        update_seeds: false,
        delete_seeds: false,
        block_seeds: false,
      },
      {
        add_raw_material: false,
        view_raw_material: false,
        update_raw_material: false,
        delete_raw_material: false,
        block_raw_material: false,
      },
      {
        add_land_broker: false,
        view_land_broker: false,
        update_land_broker: false,
        delete_land_broker: false,
        block_land_broker: false,
      },
      {
        add_transport: false,
        view_transport: false,
        update_transport: false,
        delete_transport: false,
        block_transport: false,
      },
      {
        add_accounts: false,
        view_accounts: false,
        update_accounts: false,
        delete_accounts: false,
        block_accounts: false,
      },
      {
        agriculture: false,
      },
      {
        logistics: false,
      },
    ],
  },
  {
    role: 'golden_member',
    permissions: [
      {
        add_users: false,
        view_users: false,
        update_users: false,
        block_users: false,
        delete_users: false,
      },
      {
        add_vendor: false,
        view_vendor: true,
        update_vendor: false,
        delete_vendor: false,
        block_vendor: false,
      },
      {
        add_wholesaler: false,
        view_wholesaler: true,
        update_wholesaler: false,
        delete_wholesaler: false,
        block_wholesaler: false,
      },
      {
        add_farmer: false,
        view_farmer: true,
        update_farmer: false,
        delete_farmer: false,
        block_farmer: false,
      },
      {
        add_machinery: false,
        view_machinery: true,
        update_machinery: false,
        delete_machinery: false,
        block_machinery: false,
      },
      {
        add_seeds: false,
        view_seeds: true,
        update_seeds: false,
        delete_seeds: false,
        block_seeds: false,
      },
      {
        add_raw_material: false,
        view_raw_material: true,
        update_raw_material: false,
        delete_raw_material: false,
        block_raw_material: false,
      },
      {
        add_land_broker: false,
        view_land_broker: true,
        update_land_broker: false,
        delete_land_broker: false,
        block_land_broker: false,
      },
      {
        add_transport: false,
        view_transport: true,
        update_transport: false,
        delete_transport: false,
        block_transport: false,
      },
      {
        add_accounts: false,
        view_accounts: true,
        update_accounts: false,
        delete_accounts: false,
        block_accounts: false,
      },
      {
        agriculture: true,
      },
      {
        logistics: true,
      },
    ],
  },
  {
    role: 'wholesaler',
    permissions: [
      {
        add_users: false,
        view_users: false,
        update_users: false,
        block_users: false,
        delete_users: false,
      },
      {
        add_vendor: false,
        view_vendor: true,
        update_vendor: false,
        delete_vendor: false,
        block_vendor: false,
      },
      {
        add_wholesaler: false,
        view_wholesaler: true,
        update_wholesaler: false,
        delete_wholesaler: false,
        block_wholesaler: false,
      },
      {
        add_farmer: false,
        view_farmer: true,
        update_farmer: false,
        delete_farmer: false,
        block_farmer: false,
      },
      {
        add_machinery: false,
        view_machinery: false,
        update_machinery: false,
        delete_machinery: false,
        block_machinery: false,
      },
      {
        add_seeds: false,
        view_seeds: false,
        update_seeds: false,
        delete_seeds: false,
        block_seeds: false,
      },
      {
        add_raw_material: false,
        view_raw_material: false,
        update_raw_material: false,
        delete_raw_material: false,
        block_raw_material: false,
      },
      {
        add_land_broker: false,
        view_land_broker: false,
        update_land_broker: false,
        delete_land_broker: false,
        block_land_broker: false,
      },
      {
        add_transport: false,
        view_transport: false,
        update_transport: false,
        delete_transport: false,
        block_transport: false,
      },
      {
        add_accounts: false,
        view_accounts: false,
        update_accounts: false,
        delete_accounts: false,
        block_accounts: false,
      },
      {
        agriculture: false,
      },
      {
        logistics: false,
      },
    ],
  },
  {
    role: 'agriculture',
    permissions: [
      {
        add_users: false,
        view_users: false,
        update_users: false,
        block_users: false,
        delete_users: false,
      },
      {
        add_vendor: false,
        view_vendor: false,
        update_vendor: false,
        delete_vendor: false,
        block_vendor: false,
      },
      {
        add_wholesaler: false,
        view_wholesaler: false,
        update_wholesaler: false,
        delete_wholesaler: false,
        block_wholesaler: false,
      },
      {
        add_farmer: false,
        view_farmer: true,
        update_farmer: false,
        delete_farmer: false,
        block_farmer: false,
      },
      {
        add_machinery: false,
        view_machinery: false,
        update_machinery: false,
        delete_machinery: false,
        block_machinery: false,
      },
      {
        add_seeds: false,
        view_seeds: false,
        update_seeds: false,
        delete_seeds: false,
        block_seeds: false,
      },
      {
        add_raw_material: false,
        view_raw_material: false,
        update_raw_material: false,
        delete_raw_material: false,
        block_raw_material: false,
      },
      {
        add_land_broker: false,
        view_land_broker: false,
        update_land_broker: false,
        delete_land_broker: false,
        block_land_broker: false,
      },
      {
        add_transport: false,
        view_transport: true,
        update_transport: false,
        delete_transport: false,
        block_transport: false,
      },
      {
        add_accounts: false,
        view_accounts: false,
        update_accounts: false,
        delete_accounts: false,
        block_accounts: false,
      },
      {
        agriculture: false,
      },
      {
        logistics: true,
      },
    ],
  },
  {
    role: 'logistics',
    permissions: [
      {
        add_users: false,
        view_users: false,
        update_users: false,
        block_users: false,
        delete_users: false,
      },
      {
        add_vendor: false,
        view_vendor: false,
        update_vendor: false,
        delete_vendor: false,
        block_vendor: false,
      },
      {
        add_wholesaler: false,
        view_wholesaler: true,
        update_wholesaler: false,
        delete_wholesaler: false,
        block_wholesaler: false,
      },
      {
        add_farmer: false,
        view_farmer: true,
        update_farmer: false,
        delete_farmer: false,
        block_farmer: false,
      },
      {
        add_machinery: false,
        view_machinery: false,
        update_machinery: false,
        delete_machinery: false,
        block_machinery: false,
      },
      {
        add_seeds: false,
        view_seeds: false,
        update_seeds: false,
        delete_seeds: false,
        block_seeds: false,
      },
      {
        add_raw_material: false,
        view_raw_material: false,
        update_raw_material: false,
        delete_raw_material: false,
        block_raw_material: false,
      },
      {
        add_land_broker: false,
        view_land_broker: false,
        update_land_broker: false,
        delete_land_broker: false,
        block_land_broker: false,
      },
      {
        add_transport: false,
        view_transport: true,
        update_transport: false,
        delete_transport: false,
        block_transport: false,
      },
      {
        add_accounts: false,
        view_accounts: true,
        update_accounts: false,
        delete_accounts: false,
        block_accounts: false,
      },
      {
        agriculture: false,
      },
      {
        logistics: true,
      },
    ],
  },
]
export default permissions
